# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: position.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='position.proto',
  package='',
  syntax='proto2',
  serialized_options=b'\n\010maincodeB\014positiontest',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0eposition.proto\"\xad\x02\n\x08position\x12\x14\n\x0cmin_position\x18\x01 \x02(\x08\x12\x12\n\nitems_html\x18\x02 \x02(\t\x12\x18\n\x10new_latent_count\x18\x03 \x02(\x01\x12\x1c\n\x04\x64\x61ta\x18\x04 \x02(\x0b\x32\x0e.position.DATA\x12\x0c\n\x04time\x18\x05 \x02(\t\x12\r\n\x05time2\x18\x06 \x02(\t\x12\x1a\n\x0enumericalArray\x18\x07 \x03(\x05\x42\x02\x10\x01\x12\x13\n\x0bStringArray\x18\x08 \x03(\t\x12$\n\x08objArray\x18\t \x03(\x0b\x32\x12.position.OBJARRAY\x1a$\n\x04\x44\x41TA\x12\x0e\n\x06length\x18\x01 \x02(\x05\x12\x0c\n\x04text\x18\x02 \x02(\t\x1a%\n\x08OBJARRAY\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0b\n\x03\x61ge\x18\x02 \x02(\x05\x42\x18\n\x08maincodeB\x0cpositiontest'
)




_POSITION_DATA = _descriptor.Descriptor(
  name='DATA',
  full_name='position.DATA',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='length', full_name='position.DATA.length', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='text', full_name='position.DATA.text', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=245,
  serialized_end=281,
)

_POSITION_OBJARRAY = _descriptor.Descriptor(
  name='OBJARRAY',
  full_name='position.OBJARRAY',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='position.OBJARRAY.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='age', full_name='position.OBJARRAY.age', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=283,
  serialized_end=320,
)

_POSITION = _descriptor.Descriptor(
  name='position',
  full_name='position',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='min_position', full_name='position.min_position', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='items_html', full_name='position.items_html', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='new_latent_count', full_name='position.new_latent_count', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='position.data', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time', full_name='position.time', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time2', full_name='position.time2', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='numericalArray', full_name='position.numericalArray', index=6,
      number=7, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='StringArray', full_name='position.StringArray', index=7,
      number=8, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='objArray', full_name='position.objArray', index=8,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_POSITION_DATA, _POSITION_OBJARRAY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=320,
)

_POSITION_DATA.containing_type = _POSITION
_POSITION_OBJARRAY.containing_type = _POSITION
_POSITION.fields_by_name['data'].message_type = _POSITION_DATA
_POSITION.fields_by_name['objArray'].message_type = _POSITION_OBJARRAY
DESCRIPTOR.message_types_by_name['position'] = _POSITION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

position = _reflection.GeneratedProtocolMessageType('position', (_message.Message,), {

  'DATA' : _reflection.GeneratedProtocolMessageType('DATA', (_message.Message,), {
    'DESCRIPTOR' : _POSITION_DATA,
    '__module__' : 'position_pb2'
    # @@protoc_insertion_point(class_scope:position.DATA)
    })
  ,

  'OBJARRAY' : _reflection.GeneratedProtocolMessageType('OBJARRAY', (_message.Message,), {
    'DESCRIPTOR' : _POSITION_OBJARRAY,
    '__module__' : 'position_pb2'
    # @@protoc_insertion_point(class_scope:position.OBJARRAY)
    })
  ,
  'DESCRIPTOR' : _POSITION,
  '__module__' : 'position_pb2'
  # @@protoc_insertion_point(class_scope:position)
  })
_sym_db.RegisterMessage(position)
_sym_db.RegisterMessage(position.DATA)
_sym_db.RegisterMessage(position.OBJARRAY)


DESCRIPTOR._options = None
_POSITION.fields_by_name['numericalArray']._options = None
# @@protoc_insertion_point(module_scope)
